### ISSUE TITLE
Code works perfectly but ...

### ISSUE THREAD

**Issue by meisamsafavi** [jremington/LSM9DS1-AHRS#1]
Hey,
First of all thanks a lot for your great code its awesome but i cant figure it out how to use the sensor with other Madgwick because of NED or NWU or ... 
Can you please explain how to figure out the NED system to be able to use the sensor with other filters as well as yours.
thanks agian.

**Comment by jremington** [comment]
NED or NWU (etc.) tells  you how the sensor axes are aligned to the Earth wnen yaw=0, pitch=0 and roll=0.  

NED means X points to magnetic or true North, Y is East and Z is Down.  NWU means Y is West, Z is up.
