### ISSUE TITLE
Trouble with deltat while performing other op on arduino nano

### ISSUE THREAD

**Issue by Mixou26** [jremington/LSM9DS1-AHRS#2]
Hello jremington, 
Thanks for the code, it is really interessting and it's working directly, which is nice :)
I'm experiencing some issue with yaw calculation as soon as I try to perform other task with arduino (calculate average yaw, doing other stuff).
I think the problem comes from the using of deltat for the quaternion.
For exemple, if I print yaw with nothing else: works fine, yaw value is constant
If I add delay(500), the yaw value is just not stable and shows large variations.
Have you experienced such an issue?
Do you think there is a simple way to deal with this?
Thanks
Best regards
Mix

**Comment by jremington** [comment]
The loop update time has to be short, otherwise the numerical integration becomes extremely inaccurate.  You can't even print every update cycle!

If you want to do a significant amount of "other stuff" between sensor reads and quaternion update, you will need a faster processor.
