### ISSUE TITLE
Tilt compensation for model rocket

### ISSUE THREAD

**Issue by coryjonsmith** [jremington/LSM9DS1-AHRS#4]
I am looking to utilize an AHRS algorithm like this in a model rocket.  The orientation of the IMU will be such that the x axis will be pointing into the sky perpendicular to the ground.  If the x-axis was parallel with the ground the magnetometer would contribute to the  yaw calculation relative to north.  However, in my configuration it seems that the magnetometer would contribute to the roll calculation relative to north.  Is this something that is taken into account in your tilt compensated compass code?

**Comment by jremington** [comment]
The tilt compensated compass code assumes that there is no acceleration other than due to gravity.  It won't work at all in a rocket.
